# Python generated by GitHub Copilot

from __future__ import annotations


class Agent:
    def __init__(self, name: str):
        self.name = name

    def think(self, prompt: str) -> str:
        return f"[{self.name}] Processing request: {prompt}"

    def respond(self, prompt: str) -> str:
        analysis = self.think(prompt)
        return f"{analysis}\nResponse: I am an agentic AI assistant ready to help."


def main() -> None:
    agent = Agent("Agentic-AI")
    prompt = "Plan a simple workflow for a research assistant."
    print(agent.respond(prompt))


if __name__ == "__main__":
    main()
